// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'MobileVerificationModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MobileVerificationModel _$MobileVerificationModelFromJson(
    Map<String, dynamic> json) {
  return MobileVerificationModel(
    custId: json['custId'] as int,
    custName: json['custName'] as String,
    phoneNumber: json['phoneNumber'] as String,
    whatsappNo: json['whatsappNo'] as String,
    emailId: json['emailId'] as String,
    profilePic: json['profilePic'] as String,
    gender: json['gender'] as int,
    custDob: json['custDob'] as String,
    ageGroup: json['ageGroup'] as String,
    langId: json['langId'] as int,
    compId: json['compId'] as int,
    cityId: json['cityId'] as int,
    frId: json['frId'] as int,
    isBuissHead: json['isBuissHead'] as int,
    companyName: json['companyName'] as String,
    gstNo: json['gstNo'] as String,
    address: json['address'] as String,
    isActive: json['isActive'] as int,
    delStatus: json['delStatus'] as int,
    custAddPlatform: json['custAddPlatform'] as int,
    custAddDatetime: json['custAddDatetime'] as String,
    addedFromType: json['addedFromType'] as int,
    userId: json['userId'] as int,
    isPremiumCust: json['isPremiumCust'] as int,
    exInt1: json['exInt1'] as int,
    exInt2: json['exInt2'] as int,
    exInt3: json['exInt3'] as int,
    exInt4: json['exInt4'] as int,
    exInt5: json['exInt5'] as int,
    exVar1: json['exVar1'] as String,
    exVar2: json['exVar2'] as String,
    exVar3: json['exVar3'] as String,
    exVar4: json['exVar4'] as String,
    exVar5: json['exVar5'] as String,
    exFloat1: json['exFloat1'] as int,
    exFloat2: json['exFloat2'] as int,
    exFloat3: json['exFloat3'] as int,
    exFloat4: json['exFloat4'] as int,
    exFloat5: json['exFloat5'] as int,
    langName: json['langName'] as String,
    cityName: json['cityName'] as String,
  );
}

Map<String, dynamic> _$MobileVerificationModelToJson(
        MobileVerificationModel instance) =>
    <String, dynamic>{
      'custId': instance.custId,
      'gender': instance.gender,
      'langId': instance.langId,
      'compId': instance.compId,
      'cityId': instance.cityId,
      'frId': instance.frId,
      'isBuissHead': instance.isBuissHead,
      'isActive': instance.isActive,
      'delStatus': instance.delStatus,
      'custAddPlatform': instance.custAddPlatform,
      'addedFromType': instance.addedFromType,
      'userId': instance.userId,
      'isPremiumCust': instance.isPremiumCust,
      'exInt1': instance.exInt1,
      'exInt2': instance.exInt2,
      'exInt3': instance.exInt3,
      'exInt4': instance.exInt4,
      'exInt5': instance.exInt5,
      'exFloat1': instance.exFloat1,
      'exFloat2': instance.exFloat2,
      'exFloat3': instance.exFloat3,
      'exFloat4': instance.exFloat4,
      'exFloat5': instance.exFloat5,
      'custName': instance.custName,
      'phoneNumber': instance.phoneNumber,
      'whatsappNo': instance.whatsappNo,
      'emailId': instance.emailId,
      'profilePic': instance.profilePic,
      'custDob': instance.custDob,
      'ageGroup': instance.ageGroup,
      'companyName': instance.companyName,
      'gstNo': instance.gstNo,
      'address': instance.address,
      'custAddDatetime': instance.custAddDatetime,
      'exVar1': instance.exVar1,
      'exVar2': instance.exVar2,
      'exVar3': instance.exVar3,
      'exVar4': instance.exVar4,
      'exVar5': instance.exVar5,
      'langName': instance.langName,
      'cityName': instance.cityName,
    };
