class OrderHeader{
   int orderId,frId,custId,status,discAmt,itemDiscAmt,orderStatus,paidStatus,paymentMethod,cityId,areaId,addressId,insertUserId,
   orderPlatform,delStatus,offerId,orderDeliveredBy,exInt1,exInt2,exInt3,exInt4,exFloat1,exFloat2,exFloat3,exFloat4,deliveryType,
   deliveryInstId,deliveryCharges,paymentSubMode,isAgent;
  String orderNo,orderDate,address,whatsappNo,landmark,deliveryDate,deliveryTime,insertDateTime,exVar1,exVar2,billingName,
  billingAddress,deliveryInstText,uuidNo;
  double taxableAmt,cgstAmt,sgstAmt,igstAmt,taxAmt,totalAmt,deliveryKm;
  

  OrderHeader(
      {this.orderId,
      this.orderNo,
      this.orderDate,
      this.frId,
      this.custId,
      this.status,
      this.taxableAmt,
      this.cgstAmt,
      this.sgstAmt,
      this.igstAmt,
      this.discAmt,
      this.itemDiscAmt,
      this.taxAmt,
      this.totalAmt,
      this.orderStatus,
      this.paidStatus,
      this.paymentMethod,
      this.cityId,
      this.areaId,
      this.addressId,
      this.address,
      this.whatsappNo,
      this.landmark,
      this.deliveryDate,
      this.deliveryTime,
      this.insertDateTime,
      this.insertUserId,
      this.orderPlatform,
      this.delStatus,
      this.offerId,
      this.orderDeliveredBy,
      this.exInt1,
      this.exInt2,
      this.exInt3,
      this.exInt4,
      this.exVar1,
      this.exVar2,
      this.exFloat1,
      this.exFloat2,
      this.exFloat3,
      this.exFloat4,
      this.billingName,
      this.billingAddress,
      this.deliveryType,
      this.deliveryInstId,
      this.deliveryInstText,
      this.deliveryKm,
      this.deliveryCharges,
      this.paymentSubMode,
      this.isAgent,
      this.uuidNo});

}